name: youtube_dowloader
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  youtube_explode_dart: ^1.12.4
  console: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
